config/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import main_page
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', main_page),
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('common/', include('common.urls')),
    path('analysis/', include('analysis.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.main_page, name='main'),
    path('menu/', views.menu_page, name='menu'),
    path('review/create/', views.review_create, name='review_create'),
    path('review/', views.review_display, name='review_display'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

LABEL_TO_IDX = {'': -1, '제육볶음': 0, '김밥': 1, '오무라이스': 2, '돈까스': 3, '라면': 4, '삼계탕': 5, '떡볶이': 6}
IDX_TO_LABEL = {v: k for k, v in LABEL_TO_IDX.items()}

# Create your models here.
class Review(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    food_type = models.CharField(max_length=1, choices=[(str(k), v) for k, v in IDX_TO_LABEL.items()], default=-1)
    rating = models.SmallIntegerField(choices=[(i, i) for i in range(1, 1 + 5)])
    prob = models.FloatField(default=-1)
    create_date = models.DateTimeField()

class ReviewImage(models.Model):
    review_id = models.ForeignKey(Review, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='review_images/')
    upload_date = models.DateTimeField()

main/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['content', 'rating']
        labels = {
            'content': '내용',
            'rating': '별점',
        }

main/views.py
import threading
from django import db
from django.shortcuts import render
from django.http import HttpResponse
from django.utils import timezone
from django.core.paginator import Paginator
from django.views.decorators.csrf import csrf_exempt
from .models import ReviewImage, Review
from .forms import ReviewForm
from grpc_ai_client.ai_client import GrpcClient
from django.contrib.auth.decorators import login_required

# Create your views here.
def main_page(request):
    return render(request, 'main/main.html')

def menu_page(request):
    return render(request, 'main/menu.html')

@csrf_exempt
@login_required(login_url='common:login')
def review_create(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        
        if form.is_valid():
            review = form.save(commit=False)
            review.author = request.user
            review.create_date = timezone.now()
            review.save()

            # POST 이미지 처리
            for i, image in enumerate(request.FILES.getlist('image')):
                image_bytes = image.read()
                review_image = ReviewImage(review_id=review, image=image, upload_date=timezone.now())
                review_image.save()

                if i == 0:
                    t = threading.Thread(target=inference_thread_func, args=(review, 'localhost', '50051', review.id, image_bytes))
                    t.start()
    else:
        form = ReviewForm()

    return render(request, 'main/review_create.html', {'form': form})
    
def review_display(request):
    objects = Review.objects.order_by('-create_date')
    per_page = 10

    # Paginator
    paginator = Paginator(objects, per_page=per_page)
    page = request.GET.get('page', 1)
    page_obj = paginator.get_page(page)

    # Page indexes
    start_page = (page_obj.number//per_page) * 10 + 1
    prev_start_page = start_page-per_page if start_page-per_page >= 1 else None
    last_page = min(start_page + per_page - 1, paginator.num_pages)
    next_start_page = last_page + 1 if last_page + 1 <= paginator.num_pages else None

    context = {
        'review_list': page_obj,
        'page_range': range(start_page, last_page+1),
        'prev_start_page': prev_start_page,
        'next_start_page': next_start_page,
    }                   

    return render(request, 'main/review_display.html', context)

def inference_thread_func(review, host, port, id, image_bytes):
    result = GrpcClient.inference_request(host, port, id, image_bytes)
    review.food_type = result['food_type']
    review.prob = result['probability']
    review.save()

    # 명시적 종료 안할경우 thread 종료되어도 connection이 남아있음
    db.connections.close_all()

templates/main/main.html
{% extends 'base.html' %}
{% block content %}
<h2>메인페이지</h2>
{% endblock %}

templates/main/menu.html
{% extends 'base.html' %}
{% block content %}
<h1>Menu</h1>
<ui>
    <li>라면</i>
    <li>피자</i>
</ui>
{% endblock %}

templates/main/review_create.html
{% extends 'base.html' %}
{% block content %}
<h2>리뷰작성</h2>
{% if form.errors %}
<div>
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <textarea name="content" id="content" placeholder="내용을 입력해주세요."></textarea><br>
    <label for="rating">별점</label>
    <input type="number" id="rating" name="rating" min="1" max="5" value="5"><label>점</label><br>
    <input type="file" name="image" id="image" accept="image/jpeg, image/png" multiple><br>
    <input type="submit" value="작성하기">
</form>
{% endblock %}

templates/main/review_display.html
{% extends 'base.html' %}
{% block content %}
<h2>리뷰보기</h2>
{% for review in review_list %}
<p>{{ review.content }}</p>
<p>category : {{ review.get_food_type_display }}</p>
{% for review_image in review.reviewimage_set.all %}
<img src="{{ review_image.image.url }}">
{% endfor %}
<hr>
{% endfor %}

<h3>페이지네이션</h3>
<ul>
    {% if prev_start_page %}
    <li><a href="{% url 'main:review_display' %}?page={{ prev_start_page }}">앞</a></li>
    {% else %}
    <li>앞</li>
    {% endif %}

    {% for idx in page_range %}
    <li><a href="{% url 'main:review_display' %}?page={{ idx }}">{{ idx }}</a></li>
    {% endfor %}

    {% if next_start_page %}
    <li><a href="{% url 'main:review_display' %}?page={{ next_start_page }}">뒤</a></li>
    {% else %}
    <li>뒤</li>
    {% endif %}
</ul>
{% endblock %}