analysis/urls.py
from django.urls import path
from . import views

app_name = 'analysis'

urlpatterns = [
    path('', views.review_analysis, name='review_analysis'),
]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import main_page
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', main_page),
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('common/', include('common.urls')),
    path('analysis/', include('analysis.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.main_page, name='main'),
    path('menu/', views.menu_page, name='menu'),
    path('review/create/', views.review_create, name='review_create'),
    path('review/', views.review_display, name='review_display'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Food Review</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">
</head>
<body>
{% include 'navbar.html' %}
{% block content %}
{% endblock %}
</body>
</html>

templates/navbar.html
<div class="container">
  <nav class="navbar navbar-expand">
      <a class="navbar-brand p-2" href="{% url 'main:main' %}">FoodReview</a>
      <div class="container-fluid">
          <ul class="navbar-nav me-auto">
              <li class="nav-item"><a class="nav-link active" href="{% url 'main:menu' %}">메뉴</a></li>
              <li class="nav-item"><a class="nav-link active" href="{% url 'main:review_display' %}">리뷰</a></li>
              <li class="nav-item"><a class="nav-link active" href="{% url 'main:review_create' %}">리뷰작성</a></li>
              <li class="nav-item"><a class="nav-link active" href="{% url 'analysis:review_analysis' %}">리뷰분석</a></li>
          </ul>
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
            <li class="nav-item"><span class="nav-link active">{{ user.username }}님 환영합니다.</span></li>
            <li class="nav-item"><a class="nav-link active" href="{% url 'common:logout' %}">로그아웃</a></li>
            {% else %}
            <li class="nav-item"><a class="nav-link active" href="{% url 'common:login' %}">로그인</a></li>
            <li class="nav-item"><a class="nav-link active" href="{% url 'common:signup' %}">회원가입</a></li>
            {% endif %}
          </ul>
      </div>
  </nav>
</div>